title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
title: Quentin Ikuta's Website
description: This website features everything related to Quentin Ikuta including data analysis, writing, farming, cookies, and Dot the cat.
