title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
title: Quentin Ikuta
description: |
  Forester.
  MS in Forestry from the University of Minnesota. 

#Occupation: Forester. Education: Masters Degree in Natural Resources Science and Management from the University of Minnesota.
